import React, { useState } from "react";
import { 
  FileText, 
  HelpCircle, 
  Download, 
  ChevronRight, 
  BookOpen, 
  CheckCircle2, 
  List, 
  Sparkles 
} from "lucide-react";
import { EduDocument } from "../types";

interface NotesTabProps {
  document: EduDocument | null;
}

export default function NotesTab({ document }: NotesTabProps) {
  const [activeSubTab, setActiveSubTab] = useState<"summary" | "topics" | "revision" | "flashcards" | "keywords">("summary");
  const [currentFlashcardIndex, setCurrentFlashcardIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);

  if (!document) {
    return (
      <div className="flex flex-col items-center justify-center p-12 text-center h-[70vh]">
        <div className="w-16 h-16 bg-slate-100 dark:bg-slate-800 rounded-2xl flex items-center justify-center text-slate-400 dark:text-slate-500 mb-4">
          <BookOpen className="w-8 h-8" />
        </div>
        <h3 className="text-lg font-bold text-slate-700 dark:text-slate-300">
          No Document Selected
        </h3>
        <p className="text-sm text-slate-400 mt-2 max-w-sm">
          Please select or upload a document on your primary Dashboard first to view study notes.
        </p>
      </div>
    );
  }

  // Handle Note Downloader
  const handleDownloadNotes = () => {
    const rawContent = `
========================================
STUDY BUNDLE: ${document.name.toUpperCase()}
Generated by DOC - MIND AI Learning Platform
========================================

1. EXECUTIVE SUMMARY
----------------------------------------
${document.summary}

2. IMPORTANT TOPICS & FORMULA SHEETS
----------------------------------------
${document.importantTopics}

3. COMPACT REVISION NOTES
----------------------------------------
${document.revisionNotes}

4. KEYWORD GLOSSARY
----------------------------------------
${document.keywords.map((kw, i) => `${i+1}. ${kw.term}: ${kw.definition}`).join("\n")}

5. FLASHCARDS
----------------------------------------
${document.flashcards.map((fc, i) => `Q${i+1}: ${fc.question}\nA${i+1}: ${fc.answer}`).join("\n\n")}
    `;

    const blob = new Blob([rawContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = window.document.createElement("a");
    link.href = url;
    link.download = `${document.name.split(".")[0]}_DOC_-_MIND_AI_Notes.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleNextFlashcard = () => {
    setIsFlipped(false);
    setTimeout(() => {
      setCurrentFlashcardIndex((prev) => (prev + 1) % document.flashcards.length);
    }, 150);
  };

  const handlePrevFlashcard = () => {
    setIsFlipped(false);
    setTimeout(() => {
      setCurrentFlashcardIndex((prev) => (prev - 1 + document.flashcards.length) % document.flashcards.length);
    }, 150);
  };

  return (
    <div className="max-w-5xl mx-auto p-4 md:p-6 space-y-6">
      {/* Header and Download Button */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-100 dark:border-white/10 pb-5">
        <div>
          <span className="text-[10px] font-mono tracking-widest font-bold uppercase text-cyan-400">
            AI NOTES HUB
          </span>
          <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100 tracking-tight mt-1">
            {document.name}
          </h2>
        </div>

        <button
          onClick={handleDownloadNotes}
          className="flex items-center space-x-2 px-4 py-2 bg-gradient-to-r from-cyan-500 to-indigo-500 hover:from-cyan-400 hover:to-indigo-400 text-slate-950 rounded-xl text-sm font-semibold shadow-md transition"
        >
          <Download className="w-4 h-4" />
          <span>Download Study Bundle</span>
        </button>
      </div>

      {/* Sub Tabs Navigation */}
      <div className="flex border-b border-slate-100 dark:border-white/10 overflow-x-auto gap-2 py-1 scrollbar-none">
        {(["summary", "topics", "revision", "flashcards", "keywords"] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveSubTab(tab)}
            className={`px-4 py-2.5 rounded-lg text-xs font-semibold uppercase tracking-wider shrink-0 transition ${
              activeSubTab === tab
                ? "bg-cyan-500/10 text-cyan-400 border border-cyan-500/20"
                : "text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
            }`}
          >
            {tab === "summary" && "Executive Summary"}
            {tab === "topics" && "Topics & Formulas"}
            {tab === "revision" && "Revision Notes"}
            {tab === "flashcards" && "AI Flashcards"}
            {tab === "keywords" && "Keywords Glossary"}
          </button>
        ))}
      </div>

      {/* Sub Tab Content Rendering */}
      <div className="bg-white dark:bg-white/[0.03] backdrop-blur-sm rounded-2xl border border-slate-100 dark:border-white/10 p-6 shadow-sm min-h-[400px]">
        {/* TAB 1: Summary */}
        {activeSubTab === "summary" && (
          <div className="prose dark:prose-invert max-w-none text-slate-700 dark:text-slate-300 text-sm leading-relaxed space-y-4">
            <div className="flex items-center space-x-2 text-cyan-400 mb-2">
              <Sparkles className="w-4 h-4" />
              <span className="font-semibold text-xs tracking-wider uppercase font-mono">
                AI Summary Synopsis
              </span>
            </div>
            {document.summary ? (
              <div className="whitespace-pre-wrap">{document.summary}</div>
            ) : (
              <p className="text-slate-400 text-xs italic">Summary loading or unavailable...</p>
            )}
          </div>
        )}

        {/* TAB 2: Topics */}
        {activeSubTab === "topics" && (
          <div className="prose dark:prose-invert max-w-none text-slate-700 dark:text-slate-300 text-sm leading-relaxed space-y-4">
            <div className="flex items-center space-x-2 text-cyan-400 mb-2">
              <List className="w-4 h-4" />
              <span className="font-semibold text-xs tracking-wider uppercase font-mono">
                Important Chapters & Formula Guides
              </span>
            </div>
            {document.importantTopics ? (
              <div className="whitespace-pre-wrap">{document.importantTopics}</div>
            ) : (
              <p className="text-slate-400 text-xs italic">Topics list unavailable...</p>
            )}
          </div>
        )}

        {/* TAB 3: Revision */}
        {activeSubTab === "revision" && (
          <div className="prose dark:prose-invert max-w-none text-slate-700 dark:text-slate-300 text-sm leading-relaxed space-y-4">
            <div className="flex items-center space-x-2 text-cyan-400 mb-2">
              <CheckCircle2 className="w-4 h-4" />
              <span className="font-semibold text-xs tracking-wider uppercase font-mono">
                High-Yield Revision Cheat Sheets
              </span>
            </div>
            {document.revisionNotes ? (
              <div className="whitespace-pre-wrap">{document.revisionNotes}</div>
            ) : (
              <p className="text-slate-400 text-xs italic">Revision notes unavailable...</p>
            )}
          </div>
        )}

        {/* TAB 4: Flashcards */}
        {activeSubTab === "flashcards" && (
          <div className="flex flex-col items-center justify-center space-y-6 py-6">
            <div className="text-center">
              <p className="text-xs font-mono tracking-wider text-slate-400 font-semibold uppercase">
                Flashcard {currentFlashcardIndex + 1} of {document.flashcards.length}
              </p>
            </div>

            {/* Interactive Flipper Card */}
            {document.flashcards.length > 0 ? (
              <div 
                onClick={() => setIsFlipped(!isFlipped)}
                className="w-full max-w-md h-64 cursor-pointer perspective-1000"
              >
                <div className={`relative w-full h-full duration-500 transform-style-3d ${isFlipped ? "rotate-y-180" : ""}`}>
                  
                  {/* Front Side */}
                  <div className="absolute w-full h-full backface-hidden bg-slate-50 dark:bg-white/[0.01] border border-slate-200 dark:border-white/10 rounded-2xl p-6 flex flex-col items-center justify-center text-center shadow-md">
                    <span className="text-[10px] bg-slate-200 dark:bg-white/10 px-2 py-0.5 rounded font-mono font-bold text-slate-500 dark:text-slate-400 uppercase mb-4">
                      QUESTION
                    </span>
                    <p className="text-base font-bold text-slate-800 dark:text-slate-100">
                      {document.flashcards[currentFlashcardIndex].question}
                    </p>
                    <p className="text-[10px] text-slate-400 mt-6 select-none font-mono">
                      (Click anywhere to Flip)
                    </p>
                  </div>

                  {/* Back Side */}
                  <div className="absolute w-full h-full backface-hidden rotate-y-180 bg-gradient-to-tr from-slate-950 to-slate-900 border border-cyan-500/20 rounded-2xl p-6 flex flex-col items-center justify-center text-center shadow-md text-white">
                    <span className="text-[10px] bg-cyan-500/20 text-cyan-300 px-2 py-0.5 rounded font-mono font-bold uppercase mb-4">
                      ANSWER
                    </span>
                    <p className="text-base font-semibold leading-relaxed">
                      {document.flashcards[currentFlashcardIndex].answer}
                    </p>
                    <p className="text-[10px] text-slate-400 mt-6 select-none font-mono">
                      (Click anywhere to Flip back)
                    </p>
                  </div>

                </div>
              </div>
            ) : (
              <p className="text-slate-400 text-xs italic">No Flashcards generated.</p>
            )}

            {/* Slider Controls */}
            {document.flashcards.length > 0 && (
              <div className="flex items-center space-x-6">
                <button
                  onClick={handlePrevFlashcard}
                  className="px-4 py-2 bg-slate-100 dark:bg-white/[0.02] hover:bg-slate-200 dark:hover:bg-white/10 border border-transparent dark:border-white/5 rounded-lg text-xs font-semibold text-slate-700 dark:text-slate-200 transition"
                >
                  Prev Card
                </button>
                <button
                  onClick={handleNextFlashcard}
                  className="px-4 py-2 bg-slate-100 dark:bg-white/[0.02] hover:bg-slate-200 dark:hover:bg-white/10 border border-transparent dark:border-white/5 rounded-lg text-xs font-semibold text-slate-700 dark:text-slate-200 transition"
                >
                  Next Card
                </button>
              </div>
            )}
          </div>
        )}

        {/* TAB 5: Keywords */}
        {activeSubTab === "keywords" && (
          <div className="space-y-4">
            <h4 className="text-sm font-bold text-slate-800 dark:text-slate-100 font-mono tracking-tight mb-4">
              Terminology & Glossary
            </h4>
            {document.keywords.length > 0 ? (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {document.keywords.map((kw, i) => (
                  <div key={i} className="p-4 bg-slate-50 dark:bg-white/[0.01] rounded-xl border border-slate-100 dark:border-white/10 shadow-sm flex flex-col justify-between">
                    <div>
                      <span className="text-sm font-bold text-cyan-400 block font-mono">
                        {kw.term}
                      </span>
                      <p className="text-xs text-slate-600 dark:text-slate-300 mt-1.5 leading-relaxed">
                        {kw.definition}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-slate-400 text-xs italic">No Keywords generated.</p>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
